[extension]
name = "pg_timeseries"
repository = "https://github.com/dino2gnt/pg_timeseries_extension"
license = "PostgreSQL"
description = "Open source timeseries extension for Postgres."
homepage = "https://github.com/dino2gnt/pg_timeseries_extension"
documentation = "https://github.com/dino2gnt/pg_timeseries_extension"
categories = ["analytics"]
version = "0.1.8"

[build]
postgres_version = "15"
platform = "linux/amd64"
