---
name: pg_timeseries extension builer
run-name: Build PostgreSQL pg_timeseries extension
on:
  push:
  workflow_dispatch:

## Build and create the project on every push ...  this should be fiiiiine, right?
jobs:
  debs:
    strategy:
      max-parallel: 1
      matrix:
        pg_version: [ 13, 14, 15, 16, 17, 18 ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run Install Commands
        run: |
          sudo apt install -y postgresql-common ca-certificates
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install -y devscripts build-essential debhelper postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
# Debian packages
      - name: Create Debian packages
        run: |
          git checkout debian/control
          sed -i 's/@pgmajorversion@/${{ matrix.pg_version }}/g' debian/control
          dch -i "latest"
          debuild --no-sign
      - name: Collect Debian build artifacts
        run: |
          mkdir -p debian/artifacts
          mv ../*.deb debian/artifacts
      - name: Persist Debian build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postgresql-${{ matrix.pg_version }}-timeseries-deb
          path: debian/artifacts/*

# RPM Packages
  rpms:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:10
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        pg_version: [ 13, 14, 15, 16, 17, 18 ]
        dist: [10, 9]
        include:
          - dist: 9
            target: rocky+epel-9
          - dist: 10
            target: rocky+epel-10
    steps:
      - name: Prepare env
        run: |
          dnf -y install epel-release
          dnf -y install https://ftp.postgresql.org/pub/repos/yum/reporpms/EL-${{ matrix.dist }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          dnf -y install --enablerepo=crb postgresql${{ matrix.pg_version }}-server postgresql${{ matrix.pg_version }}-devel rpmbuild

      - name: Create RPM packages
        run: |
          mkdir -p ~/rpmbuild/SOURCES
          pwd
          ls -la
          VER=$(grep -m 1 '[[:space:]]\{6\}"version":' META.json | sed -e 's/[[:space:]]*"version":[[:space:]]*"\([^"]*\)",\{0,1\}/\1/')
          rpmbuild --define "pgmajorversion ${{ matrix.pg_version }}" --define "pgtsversion $VER" --undefine=_disable_source_fetch -bb pg_timeseries.spec
      - name: Collect RPM build artifacts
        run: |
          mkdir -p rpm/artifacts
          mv "${HOME}/rpmbuild" rpm/artifacts
      - name: Persist RPM build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pg-timeseries-${{ matrix.pg_version }}-rpm
          path: rpm/artifacts/*

# Release
  release:
    needs: [rpms, debs]
    runs-on: ubuntu-latest
    steps:
      - name: Release ${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            rpm/artifacts/rpmbuild/RPMS/**
            debian/artifacts/*.deb
